
drop table lv_athena_stage.m_pre_itbf_campaign_requirement_options
;

CREATE TABLE lv_athena_stage.m_pre_itbf_campaign_requirement_options (
	id int, 
	campaign_id int, 
	cid string,
	list_id bigint,
	session_id int,
	is_latest boolean, 
	employees_empty boolean, 
	employees_skip boolean, 
	geo_empty boolean, 
	geo_skip boolean, 
	industry_skip boolean,
	status int
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;





delete from lv_athena_stage.app_lv_campaign_requirement_options
;





drop table lv_athena_stage.m_pre_itbf_campaign_demand_mask
;

CREATE TABLE lv_athena_stage.m_pre_itbf_campaign_demand_mask(
		cid string,
		list_id bigint,
		session_id int,
		entity_type string,
		entity_demand_type string,
		bit_mask INT,
		country int,
		a_country int,
		state int,
		a_state int,
		job_level int,
		job_area int,
		job_function int,
		industry int,
		a_industry int,
		employee int,
		a_employee int,
		status int
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;





drop table lv_athena_stage.m_pre_itbf_final
;

CREATE TABLE lv_athena_stage.m_pre_itbf_final (
		cid string, 
		list_id int, 
		session_id int,
		email string, 
		contact_id bigint, 
		ext_contact_id bigint, 
		company_id bigint,
		ext_company_id bigint, 
		title string, 
		job_level_mapping string, 
		job_area_mapping string, 
		job_function_mapping string,
		industry_mapping string,
		sub_industry_mapping string,
		pv_comment string,
		prepackage_code int,
		rule_type string
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;

delete from lv_athena_stage.m_pre_itbf_final
;










drop table lv_athena_stage.m_pre_itbf_new_list_to_check
;

CREATE TABLE lv_athena_stage.m_pre_itbf_new_list_to_check  (
	id int ,
	list_id int,
	cid string,
	status int,
	prepackage_contact_count int,
	created_at timestamp,
	processed_at timestamp,
	used_at timestamp
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;





drop table lv_athena_stage.m_pre_itbf_contact_history_table
;

CREATE TABLE lv_athena_stage.m_pre_itbf_contact_history_table  (
	campaign_id int,
	entity_type string,
	entity_id int,
	ext_entity_id int,
	attribute_name string,
	value string
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;





drop table lv_athena_stage.m_pre_itbf_template_demands
;

CREATE TABLE lv_athena_stage.m_pre_itbf_template_demands  (
	cid string,
	list_id bigint,
	session_id int,
	entity_type string,
	field string,
	value string,
	status int
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;






drop table lv_athena_stage.m_pre_itbf_contact_new_collection
;

CREATE TABLE lv_athena_stage.m_pre_itbf_contact_new_collection (
	cid string,
	type bigint,
	campaign_id bigint,
	list_id bigint,
	session_id int,
	email_id bigint,
	email string,
	id bigint,
	contact_id bigint,
	ext_contact_id bigint,
	title string,
	country string,
	state string,
	contact_phone string,
	mobile_phone string,
	pv_comment string,
	company_id bigint,
	ext_company_id bigint,
	employee string,
	industry string,
	company_phone string,
	status int
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;





drop table lv_athena_stage.m_pre_itbf_approved_new_collection
;

CREATE TABLE lv_athena_stage.m_pre_itbf_approved_new_collection (
	cid string,
	list_id bigint,
	session_id int,
	contact_id bigint,
	title_approved int,
	address_approved int,
	employee_approved int,
	contact_approved int,
	status int
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;






CREATE TABLE lv_athena_stage.m_pre_itbf_industry_dict (
	industry string,
	sub_industry string
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;


insert into lv_athena_stage.m_pre_itbf_industry_dict
select i.name , s.name 
from "lv-prepackage-stage".lv_stage_hotfix.industries i
inner join "lv-prepackage-stage".lv_stage_hotfix.industries s on s.parent_id = i.id
;






CREATE TABLE lv_athena_stage.m_pre_itbf_pv_history (
	ext_contact_id bigint,
	contact_id bigint,
	pv_comment string,
	contact_phone string,
	mobile_phone string,
	company_phone string
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;




CREATE TABLE lv_athena_stage.m_pre_itbf_approve_history (
	approve_type string,
	email_id bigint,
	ext_company_id bigint, 
	date_approve timestamp, 
	value string
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;



create table lv_athena_stage.pre2_new_title_cm (
id int,
title string,
job_level string,
job_area string,
job_function string
)
LOCATION 's3://lvprepackage/iceberg'
TBLPROPERTIES (
  'table_type'='iceberg',
  'format'='parquet'
)
;



insert into lv_athena_stage.pre2_new_title_cm values 
(745,'Global Marketing Director','Director','Marketing','Senior Management'),
(746,'Global Marketing Manager','Manager','Marketing','General Management'),
(747,'Global Payroll Director','Director','Human Resources','Payroll / Benefits'),
(1325,'Senior Software Engineer','Senior Employee','IT / Computers / Electronics','Software Engineer'),
(311,'Deputy Chief Information Officer','Senior VP','IT / Computers / Electronics','Senior Management'),
(763,'Head of Information Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(1228,'Senior Finance Manager','Senior Manager','Finance / Accounting','General Management'),
(312,'Deputy Chief Information Security Officer','Senior VP','IT / Computers / Electronics','Cyber Security / Information Security'),
(1099,'Regional Accounting Manager','Manager','Finance / Accounting','Accounting'),
(1101,'Regional Hr Manager','Manager','Human Resources','General Management'),
(757,'Head Of Finance','Director','Finance / Accounting','Senior Management'),
(765,'Head of IT','Director','IT / Computers / Electronics','Senior Management'),
(1115,'Regional Vice President of Sales','VP','Sales','Sales'),
(1543,'Vice President, Investor Relations','VP','Marketing','Investor / Public / Media Relations'),
(196,'Chief Operating Officer','C-Level','Manufacturing / Production / Operations','Operations'),
(436,'Director of FP&A','Director','Finance / Accounting','Financial Planning / Advising'),
(732,'FP&A Manager','Manager','Finance / Accounting','Financial Planning / Advising'),
(1454,'Vice President Employee Benefits','VP','Human Resources','Payroll / Benefits'),
(258,'Compensation & Benefits Manager','Manager','Human Resources','Compensation / Benefit Policy'),
(451,'Director Of Information Systems','Director','IT / Computers / Electronics','Senior Management'),
(1368,'Shipping Manager','Manager','Logistics / Transportation','Shipping / Receiving / Warehousing'),
(209,'Chief Strategy Officer','C-Level','Business','Strategic Planning / Management'),
(1151,'Senior Construction Manager','Senior Manager','Building Construction','General Management'),
(417,'Director Of Facilities','Director','Installation / Maintenance / Repair','Facilities'),
(690,'Facilities Manager','Manager','Installation / Maintenance / Repair','Facilities'),
(786,'HR Supervisor','Supervisor','Human Resources','General Management'),
(1396,'Staffing Manager','Manager','Human Resources','Recruiting / Sourcing'),
(32,'Area Human Resources Manager','Manager','Human Resources','General Management'),
(485,'Director of Operations','Director','Business','Senior Management'),
(455,'Director of Information Technology','Director','IT / Computers / Electronics','General Management'),
(1419,'Talent Acquisition Manager','Manager','Human Resources','Talent Management'),
(279,'Corporate Controller','Manager','Finance / Accounting','Controller'),
(953,'Manager, Human Resources','Manager','Human Resources','General Management'),
(989,'Marketing Director','Director','Marketing','General Management'),
(421,'Director of Finance','Director','Finance / Accounting','General Management'),
(698,'Finance Director','Director','Finance / Accounting','Senior Management'),
(189,'Chief Marketing Officer','C-Level','Executives','CMO / Chief Marketing Officer'),
(471,'Director of Marketing','Director','Marketing','General Management'),
(1539,'Vice President, Human Resources','VP','Human Resources','Senior Management'),
(19,'Accounts Payable Manager','Manager','Finance / Accounting','Accounts Payable / Receivable'),
(1463,'Vice President Information Technology','VP','IT / Computers / Electronics','Senior Management'),
(1459,'Vice President Human Resources','VP','Human Resources','General Management'),
(1479,'Vice President of Human Resources','VP','Human Resources','Senior Management'),
(347,'Director Human Resources','Director','Human Resources','Senior Management'),
(638,'District Sales Manager','Manager','Sales','Sales'),
(1134,'Sales Manager','Manager','Sales','General Management'),
(1057,'President & Chief Executive Officer','C-Level','Executives','CEO'),
(1237,'Senior Human Resources Business Partner','Senior Manager','Human Resources','General Management'),
(138,'Chief Compliance Officer','C-Level','Executives','CCO / Chief Compliance Officer'),
(376,'Director of Benefits','Director','Human Resources','Payroll / Benefits'),
(1228,'Senior Finance Manager','Senior Manager','Finance / Accounting','General Management'),
(1163,'Senior Director Human Resources','Senior Director','Human Resources','Senior Management'),
(1319,'Senior Software Developer','Senior Employee','IT / Computers / Electronics','Software Development'),
(1395,'Staff Software Engineer','Individual Contributor','IT / Computers / Electronics','Software Engineer'),
(1375,'Software Developer','Individual Contributor','IT / Computers / Electronics','Software Development'),
(1425,'Tax Manager','Manager','Finance / Accounting','Tax Assessment / Collections'),
(1572,'VP of Finance','VP','Finance / Accounting','Senior Management'),
(458,'Director of IT','Director','IT / Computers / Electronics','General Management'),
(1542,'Vice President, Information Technology','VP','IT / Computers / Electronics','Senior Management'),
(514,'Director of Sales','Director','Sales','Sales'),
(65,'Billing Manager','Manager','Finance / Accounting','Collections'),
(790,'HRIS Manager','Manager','Human Resources','HR Systems Administration'),
(467,'Director of Manufacturing','Director','Manufacturing / Production / Operations','Senior Management'),
(540,'Director Software Engineering','Director','IT / Computers / Electronics','Software Engineer'),
(35,'Area Sales Manager','Manager','Sales','Sales'),
(1285,'Senior Manager, Human Resources','Senior Manager','Human Resources','General Management'),
(227,'Clinical Trial Manager','Manager','Biotech','Clinical Research'),
(182,'Chief Information Security Officer','C-Level','IT / Computers / Electronics','Cyber Security / Information Security'),
(574,'Director, Finance','Director','Finance / Accounting','Senior Management'),
(1114,'Regional Sales Manager','Manager','Sales','General Management'),
(1566,'VP Human Resources','VP','Human Resources','Senior Management'),
(557,'Director, Compensation','Director','Human Resources','Compensation / Benefit Policy'),
(704,'Financial Manager','Manager','Finance / Accounting','General Management'),
(895,'Maintenance Manager','Manager','Installation / Maintenance / Repair','General Management'),
(451,'Director Of Information Systems','Director','IT / Computers / Electronics','IT Systems Management'),
(781,'HR Director','Director','Human Resources','General Management'),
(1182,'Senior Director of Marketing','Senior Director','Marketing','Senior Management'),
(518,'Director of Sales and Marketing','Director','Marketing','Senior Management'),
(979,'Manufacturing Engineering Manager','Manager','Engineering','Industrial / Manufacturing Engineering'),
(506,'Director of Product Marketing','Director','Marketing','Brand / Product Marketing'),
(1116,'Release Manager','Manager','IT / Computers / Electronics','Devops & Application Management'),
(1209,'Senior Director, Human Resources','Senior Director','Human Resources','Senior Management'),
(633,'Director, Talent Acquisition','Director','Human Resources','Talent Management'),
(414,'Director of Engineering','Director','Engineering','General Management'),
(889,'Lead Software Engineer','Senior Employee','IT / Computers / Electronics','Software Engineer'),
(1068,'President and Chief Operating Officer','C-Level','Executives','COO / Chief Operations Officer'),
(1132,'sales director','Director','Sales','Sales'),
(533,'Director of Talent Acquisition','Director','Human Resources','Talent Management'),
(595,'Director, Information Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(1035,'Payroll Supervisor','Supervisor','Human Resources','Payroll / Benefits'),
(1231,'Senior HR Business Partner','Senior Manager','Human Resources','General Management'),
(164,'Chief Financial Officer','C-Level','Finance / Accounting','Senior Management'),
(750,'Global Supply Chain Manager','Manager','Logistics / Transportation','Supply Chain Management'),
(769,'Head of Product Marketing','Director','Marketing','Brand / Product Marketing'),
(525,'Director Of Software Engineering','Director','IT / Computers / Electronics','Software Development'),
(220,'Clinic Director','Director','Medical and Health','Hospital / Clinic'),
(219,'Client Success Manager','Manager','Customer Support / Client Services','Customer Service / Support'),
(887,'Lawyer','Individual Contributor','Legal','Law Firm Attorney'),
(1045,'Personnel Manager','Manager','Human Resources','General Management'),
(1090,'Programmer Analyst','Individual Contributor','IT / Computers / Electronics','System Analysis'),
(179,'Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(738,'General Manager','C-Level','Executives','General Manager'),
(174,'Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(12,'Accounting Manager','Manager','Finance / Accounting','Accounting'),
(802,'Human Resources Director','Director','Human Resources','Senior Management'),
(1325,'Senior Software Engineer','Senior Employee','IT / Computers / Electronics','Software Engineer'),
(445,'Director of Human Resources','Director','Human Resources','Senior Management'),
(116,'CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(699,'Finance Manager','Manager','Finance / Accounting','General Management'),
(1056,'President & CEO','C-Level','Executives','CEO'),
(867,'IT Manager','Manager','IT / Computers / Electronics','General Management'),
(203,'Chief People Officer','C-Level','Executives','CPO / Chief People Officer'),
(1092,'Purchasing Manager','Manager','Logistics / Transportation','Purchasing'),
(421,'Director of Finance','Director','Finance / Accounting','Senior Management'),
(991,'Marketing Manager','Manager','Marketing','General Management'),
(1015,'Operations Manager','Manager','Manufacturing / Production / Operations','Operations'),
(802,'Human Resources Director','Director','Human Resources','General Management'),
(593,'Director, Human Resources','Director','Human Resources','Senior Management'),
(863,'IT Director','Director','IT / Computers / Electronics','Senior Management'),
(799,'Human Resources Business Partner','Manager','Human Resources','General Management'),
(1051,'Plant Manager','Manager','Manufacturing / Production / Operations','Plant Management'),
(292,'CTO','C-Level','Executives','CTO / Chief Technology Officer'),
(1077,'President/CEO','C-Level','Executives','CEO'),
(892,'Logistics Manager','Manager','Logistics / Transportation','Logistics'),
(216,'CIO','C-Level','Executives','CIO / Chief Information Officer'),
(648,'Engineering Manager','Manager','Engineering','General Management'),
(296,'Customer Service Manager','Manager','Customer Support / Client Services','Customer Service / Support'),
(379,'Director of Business Development','Director','Sales','Business Development'),
(1297,'Senior Manufacturing Engineer','Senior Employee','Engineering','Industrial / Manufacturing Engineering'),
(1494,'Vice President of Sales','VP','Sales','Senior Management'),
(706,'Financial Planning and Analysis Manager','Manager','Finance / Accounting','Financial Planning / Advising'),
(1580,'VP of Marketing','VP','Marketing','Senior Management'),
(252,'Collections Manager','Manager','Finance / Accounting','Collections'),
(880,'Key Account Manager','Manager','Sales','Sales'),
(1472,'Vice President of Engineering','VP','Engineering','Senior Management'),
(1575,'VP of Human Resources','VP','Human Resources','Senior Management'),
(612,'Director, Marketing','Director','Marketing','Senior Management'),
(980,'Manufacturing Manager','Manager','Manufacturing / Production / Operations','General Management'),
(315,'Devops Manager','Manager','IT / Computers / Electronics','Devops & Application Management'),
(666,'Executive Director','C-Level','Executives','Senior Management'),
(865,'IT Infrastructure Manager','Manager','IT / Computers / Electronics','IT Infrastructure'),
(107,'CEO and President','C-Level','Executives','CEO'),
(435,'Director of Financial Planning and Analysis','Director','Finance / Accounting','Senior Management'),
(1175,'Senior Director of Human Resources','Senior Director','Human Resources','Senior Management'),
(459,'Director of IT Infrastructure','Director','IT / Computers / Electronics','IT Infrastructure'),
(464,'Director of Logistics','Director','Logistics / Transportation','Logistics'),
(1001,'Network Engineer','Individual Contributor','IT / Computers / Electronics','Network Systems'),
(1400,'Supply Chain Director','Director','Logistics / Transportation','Supply Chain Management'),
(307,'Data Science Manager','Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(956,'Manager, Information Technology','Manager','IT / Computers / Electronics','General Management'),
(1467,'Vice President Marketing','VP','Marketing','General Management'),
(598,'Director, Information Technology','Director','IT / Computers / Electronics','General Management'),
(1245,'Senior Information Technology Manager','Senior Manager','IT / Computers / Electronics','General Management'),
(1456,'Vice President Finance','VP','Finance / Accounting','General Management'),
(1487,'Vice President of Marketing','VP','Marketing','General Management'),
(278,'Corporate Accounting Manager','Manager','Finance / Accounting','Accounting'),
(461,'Director Of IT Operations','Director','IT / Computers / Electronics','Senior Management'),
(1058,'President & Chief Operating Officer','C-Level','Executives','COO / Chief Operations Officer'),
(1123,'Sales','Individual Contributor','Sales','Sales'),
(1210,'Senior Director, Information Security','Senior Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(1424,'Tax Director','Director','Finance / Accounting','Tax Assessment / Collections'),
(676,'Executive Vice President and Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(834,'Information Technology Director','Director','IT / Computers / Electronics','Senior Management'),
(1248,'Senior IT Manager','Senior Manager','IT / Computers / Electronics','General Management'),
(762,'Head Of Human Resources','Director','Human Resources','General Management'),
(1059,'President & COO','C-Level','Executives','COO / Chief Operations Officer'),
(1064,'President and CEO','C-Level','Executives','President'),
(225,'Clinical Research Manager','Manager','Biotech','Clinical Research'),
(1000,'Network Administrator','Individual Contributor','IT / Computers / Electronics','Network / Server Administration'),
(164,'Chief Financial Officer','C-Level','Finance / Accounting','General Management'),
(471,'Director of Marketing','Director','Marketing','Marketing Operations'),
(835,'Information Technology Infrastructure Manager','Manager','IT / Computers / Electronics','IT Infrastructure'),
(179,'Chief Information Officer','C-Level','IT / Computers / Electronics','General Management'),
(445,'Director of Human Resources','Director','Human Resources','HR Systems Administration'),
(455,'Director of Information Technology','Director','IT / Computers / Electronics','IT Systems Management'),
(767,'Head of Marketing','Director','Marketing','Senior Management'),
(26,'Accounts Receivable Supervisor','Supervisor','Finance / Accounting','Accounts Payable / Receivable'),
(75,'Business Development Manager','Manager','Sales','Business Development'),
(361,'Director IT','Director','IT / Computers / Electronics','Senior Management'),
(407,'Director of Devops','Director','IT / Computers / Electronics','Devops & Application Management'),
(1102,'Regional Human Resources Director','Director','Human Resources','Senior Management'),
(1166,'Senior Director Information Technology','Senior Director','IT / Computers / Electronics','Senior Management'),
(1234,'Senior Hr Manager','Senior Manager','Human Resources','General Management'),
(612,'Director, Marketing','Director','Marketing','General Management'),
(884,'Laboratory Manager','Manager','Medical and Health','Laboratory / Pathology'),
(919,'Manager of Human Resources','Manager','Human Resources','General Management'),
(1187,'Senior Director of Software Engineering','Senior Director','IT / Computers / Electronics','Software Engineer'),
(1293,'Senior Manager, Software Engineering','Senior Manager','IT / Computers / Electronics','Software Engineer'),
(1474,'Vice President of Finance','VP','Finance / Accounting','General Management'),
(601,'Director, IT','Director','IT / Computers / Electronics','Senior Management'),
(1072,'President, CEO','C-Level','Executives','CEO'),
(1412,'SVP, Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(639,'Ecommerce Manager','Manager','Retail','eCommerce'),
(830,'Information Systems Security Manager','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(614,'Director, Marketing Operations','Director','Marketing','Marketing Operations'),
(879,'It Systems Manager','Manager','IT / Computers / Electronics','IT Systems Management'),
(1002,'Network Manager','Manager','IT / Computers / Electronics','Network Systems'),
(1348,'Senior Vice President Finance','Senior VP','Finance / Accounting','Senior Management'),
(1417,'System Administrator','Individual Contributor','IT / Computers / Electronics','Network / Server Administration'),
(104,'CEO and Founder','C-Level','Executives','CEO'),
(500,'Director of Pharmacy','Director','Biotech','Pharmacy / Pharmaceutical'),
(735,'General Counsel','C-Level','Executives','General Counsel'),
(838,'Information Technology Manager','Manager','IT / Computers / Electronics','IT Systems Management'),
(1321,'Senior Software Development Manager','Senior Manager','IT / Computers / Electronics','Software Development'),
(1448,'Vice President and Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(7,'Accounting Controller','Manager','Finance / Accounting','Controller'),
(83,'CEO & Co Founder','C-Level','Executives','CEO'),
(468,'Director of Manufacturing Operations','Director','Manufacturing / Production / Operations','Operations'),
(508,'Director of Real Estate','Director','Real Estate','Senior Management'),
(603,'Director, IT Infrastructure','Director','IT / Computers / Electronics','IT Infrastructure'),
(666,'Executive Director','C-Level','Business','Senior Management'),
(666,'Executive Director','C-Level','Business','Strategic Planning / Management'),
(785,'HR Operations Manager','Manager','Human Resources','General Management'),
(945,'Manager, Finance','Manager','Finance / Accounting','General Management'),
(955,'Manager, Information Systems','Manager','IT / Computers / Electronics','IT Systems Management'),
(1003,'Network Technician','Individual Contributor','IT / Computers / Electronics','Network Systems'),
(1335,'Senior Tax Manager','Senior Manager','Finance / Accounting','Tax Assessment / Collections'),
(1360,'Senior Vice President, Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(1482,'Vice President of Information Technology','VP','IT / Computers / Electronics','General Management'),
(124,'Chairman and Chief Executive Officer','C-Level','Executives','CEO'),
(164,'Chief Financial Officer','C-Level','Finance / Accounting','CFO / Chief Financial Officer'),
(211,'Chief Technical Officer','C-Level','Executives','CTO / Chief Technology Officer'),
(316,'Digital Marketing Director','Director','Marketing','Digital Marketing'),
(426,'Director of Finance and Administration','Director','Finance / Accounting','Senior Management'),
(440,'Director of HR','Director','Human Resources','Senior Management'),
(580,'Director, Global Benefits','Director','Human Resources','Payroll / Benefits'),
(589,'Director, HR Operations','Director','Human Resources','Senior Management'),
(798,'Human Resources Benefits Manager','Manager','Human Resources','Payroll / Benefits'),
(1069,'PRESIDENT AND COO','C-Level','Executives','COO / Chief Operations Officer'),
(1270,'Senior Manager, Accounting','Senior Manager','Finance / Accounting','Accounting'),
(1271,'Senior Manager, Benefits','Senior Manager','Human Resources','Payroll / Benefits'),
(1303,'Senior Network Engineer','Senior Employee','IT / Computers / Electronics','Network Systems'),
(1439,'Transportation Manager','Manager','Logistics / Transportation','General Management'),
(1500,'Vice President of Software Engineering','VP','IT / Computers / Electronics','Software Engineer'),
(1525,'Vice President, Corporate Controller','VP','Finance / Accounting','Controller'),
(1594,'Vp, Chief Information Security Officer','C-Level','Executives','CISO / Chief Information Security Officer'),
(1599,'VP, Human Resources','VP','Human Resources','Senior Management'),
(353,'Director Information Technology','Director','IT / Computers / Electronics','Senior Management'),
(605,'Director, IT Operations','Director','IT / Computers / Electronics','Senior Management'),
(670,'Executive Vice President & Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(764,'Head of Information Technology','Director','IT / Computers / Electronics','Senior Management'),
(1105,'Regional Marketing Director','Director','Marketing','Senior Management'),
(1350,'Senior Vice President Human Resources','Senior VP','Human Resources','General Management'),
(1410,'SVP Human Resources','Senior VP','Human Resources','Senior Management'),
(196,'Chief Operating Officer','C-Level','Business','Senior Management'),
(281,'Corporate Human Resources Manager','Manager','Human Resources','General Management'),
(309,'Database Manager','Manager','IT / Computers / Electronics','Database Development / Administration'),
(710,'Founder','C-Level','Executives','Owner / Co-owner'),
(839,'Information Technology Operations Manager','Manager','IT / Computers / Electronics','General Management'),
(881,'Lab Manager','Manager','Medical and Health','Laboratory / Pathology'),
(905,'Manager Human Resources','Manager','Human Resources','General Management'),
(999,'National Sales Manager','Manager','Sales','Sales'),
(1152,'Senior Customer Success Manager','Senior Manager','Customer Support / Client Services','Customer Service / Support'),
(1290,'Senior Manager, Payroll','Senior Manager','Human Resources','Payroll / Benefits'),
(770,'Head Of Recruiting','Director','Human Resources','Recruiting / Sourcing'),
(1325,'Senior Software Engineer','Manager','IT / Computers / Electronics','Software Engineer'),
(1355,'Senior Vice President of Human Resources','Senior VP','Human Resources','Senior Management'),
(1435,'Territory Sales Manager','Manager','Sales','General Management'),
(69,'Board Member','C-Level','Executives','Board Member'),
(643,'Employee Benefits Account Manager','Manager','Human Resources','Payroll / Benefits'),
(702,'Financial Controller','Manager','Finance / Accounting','Financial Control'),
(944,'Manager, Data Science','Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(974,'Manager, Talent Acquisition','Manager','Human Resources','Recruiting / Sourcing'),
(1111,'Regional Sales Director','Director','Sales','Senior Management'),
(1135,'Sales Operations Manager','Manager','Sales','Sales Operations'),
(1180,'Senior Director of IT','Senior Director','IT / Computers / Electronics','Senior Management'),
(1307,'Senior Product Manager','Senior Manager','Business','Product Management'),
(1372,'Social Media Manager','Manager','Marketing','Social Media'),
(37,'Assistant Director of Human Resources','Senior Manager','Human Resources','General Management'),
(66,'Billing Supervisor','Supervisor','Finance / Accounting','Collections'),
(113,'CEO/President','C-Level','Executives','CEO'),
(174,'Chief Human Resources Officer','C-Level','Human Resources','General Management'),
(308,'Data Scientist','Individual Contributor','IT / Computers / Electronics','Business Intelligence / Data Science'),
(363,'Director IT Infrastructure','Director','IT / Computers / Electronics','IT Infrastructure'),
(481,'Director of Marketing Operations','Director','Marketing','Marketing Operations'),
(516,'Director of Sales & Marketing','Director','Marketing','General Management'),
(590,'Director, HRIS','Director','Human Resources','HR Systems Administration'),
(660,'EVP, Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(855,'Inventory Control Manager','Manager','Logistics / Transportation','Inventory Planning / Management'),
(992,'Marketing Operations Manager','Manager','Marketing','Marketing Operations'),
(1047,'Pharmacy Manager','Manager','Biotech','Pharmacy / Pharmaceutical'),
(1091,'Provost','Director','Education','Provost'),
(1136,'Sales Representative','Individual Contributor','Sales','Sales'),
(1161,'Senior Director Finance','Senior Director','Finance / Accounting','Senior Management'),
(1449,'Vice President and CIO','C-Level','Executives','CIO / Chief Information Officer'),
(1563,'VP Finance','VP','Finance / Accounting','General Management'),
(1570,'VP of Engineering','VP','Engineering','Senior Management'),
(24,'Accounts Receivable Manager','Manager','Finance / Accounting','Accounts Payable/Receivable'),
(77,'Business Manager','Manager','Business','General Management'),
(237,'Co Owner','C-Level','Executives','Owner / Co-owner'),
(284,'Corporate Purchasing Manager','Manager','Logistics / Transportation','Purchasing'),
(310,'Dean','Director','Education','Provost'),
(462,'Director Of It Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(564,'Director, Cybersecurity','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(858,'IS Manager','Manager','IT / Computers / Electronics','IT Systems Management'),
(983,'Market Manager','Manager','Sales','Sales'),
(1192,'Senior Director Software Engineering','Senior Director','IT / Computers / Electronics','Software Engineer'),
(1197,'Senior Director, Data Science','Senior Director','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1259,'Senior Manager Information Security','Senior Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(1311,'Senior Purchasing Manager','Senior Manager','Logistics / Transportation','Purchasing'),
(1342,'Senior Vice President and Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(1508,'Vice President Sales','VP','Sales','Senior Management'),
(1523,'Vice President, Compensation','VP','Human Resources','Compensation / Benefit Policy'),
(341,'Director Global Compensation','Director','Human Resources','Compensation / Benefit Policy'),
(403,'Director of Cybersecurity','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(630,'Director, Supply Chain','Director','Logistics / Transportation','Supply Chain Management'),
(685,'Executive Vice President, Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(743,'Global Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(838,'Information Technology Manager','Manager','IT / Computers / Electronics','IT Infrastructure'),
(877,'IT Support Specialist','Individual Contributor','IT / Computers / Electronics','System Admin / Desktop Support'),
(946,'Manager, Financial Planning & Analysis','Manager','Finance / Accounting','Financial Planning / Advising'),
(1048,'Plant Director','Director','Manufacturing / Production / Operations','Plant Management'),
(1084,'Product Marketing Manager','Manager','Marketing','Product Management'),
(1258,'Senior Manager Human Resources','Senior Manager','Human Resources','General Management'),
(1328,'Senior Staff Software Engineer','Senior Employee','IT / Computers / Electronics','Software Engineer'),
(24,'Accounts Receivable Manager','Manager','Finance / Accounting','Accounting'),
(245,'CO-Owner','C-Level','Executives','Owner / Co-owner'),
(356,'Director Information Technology Operations','Director','IT / Computers / Electronics','Senior Management'),
(511,'Director of Recruitment','Director','Human Resources','Recruiting / Sourcing'),
(548,'Director, Business Development','Director','Sales','Business Development'),
(623,'Director, Product Marketing','Director','Marketing','Brand / Product Marketing'),
(710,'Founder','C-Level','Executives','CEO'),
(740,'General Sales Manager','Manager','Sales','General Management'),
(793,'Human Resource Director','Director','Human Resources','General Management'),
(842,'Information Technology Security Manager','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(894,'Logistics Supervisor','Supervisor','Logistics / Transportation','Logistics'),
(1100,'Regional Finance Manager','Manager','Finance / Accounting','General Management'),
(1127,'Sales and Marketing Manager','Manager','Marketing','General Management'),
(1173,'Senior Director Of Finance','Senior Director','Finance / Accounting','General Management'),
(1280,'Senior Manager, Finance','Senior Manager','Finance / Accounting','General Management'),
(1345,'Senior Vice President and Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(1359,'Senior Vice President, Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(1442,'Treasury Manager','Manager','Finance / Accounting','Financial Control'),
(1547,'Vice President, Marketing','VP','Marketing','General Management'),
(1567,'VP Information Technology','VP','IT / Computers / Electronics','Senior Management'),
(1591,'VP Sales and Marketing','VP','Marketing','Senior Management'),
(57,'Automotive Technician','Individual Contributor','Installation / Maintenance / Repair','Automotive / Vehicle'),
(121,'Chairman & Chief Executive Officer','C-Level','Executives','CEO'),
(236,'Co Founder, CEO','C-Level','Executives','CEO'),
(306,'Data Center Manager','Manager','IT / Computers / Electronics','Data Center'),
(348,'Director Human Resources Operations','Director','Human Resources','Senior Management'),
(357,'Director Information Technology Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(399,'Director of Customer Success','Director','Customer Support / Client Services','Customer Service / Support'),
(514,'Director of Sales','Director','Sales','General Management'),
(531,'Director of Talent','Director','Human Resources','Talent Management'),
(534,'Director of Tax','Director','Finance / Accounting','Tax Assessment / Collections'),
(542,'Director Supply Chain Management','Director','Logistics / Transportation','Supply Chain Management'),
(543,'Director Talent Acquisition','Director','Human Resources','Recruiting / Sourcing'),
(587,'Director, HR Business Partner','Director','Human Resources','General Management'),
(645,'Employee Relations Director','Director','Human Resources','Compensation / Benefit Policy'),
(646,'Employee Relations Manager','Manager','Human Resources','Diversity Management / EEO / Compliance'),
(669,'Executive Director, Human Resources','Senior Director','Human Resources','Senior Management'),
(691,'Field CTO','C-Level','Executives','CTO / Chief Technology Officer'),
(951,'Manager, Human Resource','Manager','Human Resources','General Management'),
(1132,'Sales Director','Director','Sales','General Management'),
(1222,'Senior Engineering Manager','Senior Manager','Engineering','General Management'),
(1296,'Senior Manager, Total Rewards','Senior Manager','Human Resources','Compensation / Benefit Policy'),
(1300,'Senior Marketing Director','Senior Director','Marketing','Senior Management'),
(1367,'Senior Web Developer','Senior Employee','IT / Computers / Electronics','Web Developer'),
(1390,'Software Manager','Manager','IT / Computers / Electronics','Software Development'),
(1403,'Svp & Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(1404,'SVP & Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(1511,'Vice President Sales and Marketing','VP','Marketing','General Management'),
(1590,'VP Sales & Marketing','VP','Marketing','Senior Management'),
(60,'Benefits Account Manager','Manager','Human Resources','Payroll / Benefits'),
(144,'Chief Development Officer','C-Level','Executives','Other CXO'),
(190,'Chief Medical Officer','C-Level','Medical and Health','Senior Management'),
(364,'Director It Operations','Director','IT / Computers / Electronics','Senior Management'),
(365,'Director It Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(392,'Director of Compensation and Benefits','Director','Human Resources','Compensation / Benefit Policy'),
(428,'Director of Finance and Operations','Director','Finance / Accounting','Senior Management'),
(544,'Director Talent Development','Director','Human Resources','Talent Management'),
(583,'Director, Global Payroll','Director','Human Resources','Payroll / Benefits'),
(584,'Director, Global Total Rewards','Director','Human Resources','Compensation / Benefit Policy'),
(890,'Litigation Associate','Individual Contributor','Legal','Litigation'),
(906,'Manager Information Systems','Manager','IT / Computers / Electronics','IT Systems Management'),
(948,'Manager, FP&A','Manager','Finance / Accounting','Financial Planning / Advising'),
(957,'Manager, Internal Audit','Manager','Finance / Accounting','Audit'),
(966,'Manager, Payroll & Benefits','Manager','Human Resources','Payroll / Benefits'),
(1004,'News Director','Director','Journalism / Media / Entertainment','Video / Television'),
(1067,'President and Chief Executive Officer','C-Level','Executives','President'),
(1119,'Revenue Accounting Manager','Manager','Finance / Accounting','Accounting'),
(1206,'Senior Director, HR','Senior Director','Human Resources','Senior Management'),
(1284,'Senior Manager, HR Operations','Senior Manager','Human Resources','General Management'),
(1320,'Senior Software Development Engineer','Senior Employee','IT / Computers / Electronics','Software Development'),
(1340,'Senior Vice President & Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(1354,'Senior Vice President of Finance','Senior VP','Finance / Accounting','Senior Management'),
(1415,'SVP, Human Resources','Senior VP','Human Resources','Senior Management'),
(1426,'Technical Account Manager','Manager','Customer Support / Client Services','Technical Support'),
(1443,'Vice President','VP','Executives','Senior Management'),
(1445,'Vice President & Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(1450,'Vice President and General Manager','C-Level','Executives','General Manager'),
(1460,'Vice President Information Security','VP','IT / Computers / Electronics','Cyber Security / Information Security'),
(1468,'Vice President Of Accounting','VP','Finance / Accounting','Accounting'),
(1469,'Vice President of Business Development','VP','Sales','Business Development'),
(1497,'Vice President of Sales and Marketing','VP','Marketing','General Management'),
(1526,'Vice President, Cybersecurity','VP','IT / Computers / Electronics','Cyber Security / Information Security'),
(1544,'Vice President, IT','VP','IT / Computers / Electronics','Senior Management'),
(1569,'VP Marketing','VP','Marketing','General Management'),
(28,'AP Supervisor','Supervisor','Finance / Accounting','Accounts Payable / Receivable'),
(61,'Benefits and Compensation Manager','Manager','Human Resources','Compensation / Benefit Policy'),
(118,'Chairman','C-Level','Executives','Chairman'),
(203,'Chief People Officer','C-Level','Human Resources','General Management'),
(251,'Collection Manager','Manager','Finance / Accounting','Collections'),
(261,'Compensation Benefits Manager','Manager','Human Resources','Compensation / Benefit Policy'),
(355,'Director Information Technology Infrastructure','Director','IT / Computers / Electronics','IT Infrastructure'),
(383,'Director of Client Services','Director','Customer Support / Client Services','Customer Service / Support'),
(497,'Director of People Operations','Director','Human Resources','Senior Management'),
(608,'Director, IT Security and Compliance','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(657,'Evp & Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(666,'Executive Director','C-Level','Executives','Other CXO'),
(667,'Executive Director Human Resources','Senior Director','Human Resources','Senior Management'),
(668,'Executive Director of Human Resources','Senior Director','Human Resources','Senior Management'),
(705,'Financial Operations Manager','Manager','Finance / Accounting','General Management'),
(791,'Human Resource Business Partner','Manager','Human Resources','General Management'),
(829,'Information Systems Manager','Manager','IT / Computers / Electronics','General Management'),
(883,'Laboratory Director','Director','Medical and Health','Laboratory / Pathology'),
(903,'Manager Financial Planning and Analysis','Manager','Finance / Accounting','Financial Planning / Advising'),
(936,'Manager, Accounts Receivable','Manager','Finance / Accounting','Accounts Payable / Receivable'),
(1089,'Programmer','Individual Contributor','IT / Computers / Electronics','Software Development'),
(1106,'Regional Marketing Manager','Manager','Marketing','General Management'),
(1178,'Senior Director Of Information Technology','Senior Director','IT / Computers / Electronics','General Management'),
(1288,'Senior Manager, IT Infrastructure','Senior Manager','IT / Computers / Electronics','IT Infrastructure'),
(1310,'Senior Product Marketing Manager','Senior Manager','Marketing','General Management'),
(1310,'Senior Product Marketing Manager','Senior Manager','Marketing','Product Management'),
(1331,'Senior System Administrator','Senior Employee','IT / Computers / Electronics','System Admin / Desktop Support'),
(1337,'Senior Vice President & Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(1366,'Senior Vice President, Marketing','Senior VP','Marketing','Senior Management'),
(1446,'Vice President & General Manager','C-Level','Executives','General Manager'),
(1463,'Vice President Information Technology','VP','IT / Computers / Electronics','IT Infrastructure'),
(1477,'Vice President of Finance and Operations','VP','Finance / Accounting','Senior Management'),
(1522,'Vice President, Chief Information Security Officer','C-Level','Executives','CISO / Chief Information Security Officer'),
(1533,'Vice President, Finance','VP','Finance / Accounting','General Management'),
(1551,'Vice President, Sales and Marketing','VP','Marketing','Senior Management'),
(1589,'VP Sales','VP','Sales','Sales'),
(1603,'VP, Marketing','VP','Marketing','Senior Management'),
(27,'Animation Director','Director','Creative / Design','Animation / Multimedia'),
(222,'Clinical Data Manager','Manager','Biotech','Clinical Research'),
(234,'Co Founder & CTO','C-Level','Executives','CTO / Chief Technology Officer'),
(313,'Deputy Director of Human Resources','Senior Manager','Human Resources','General Management'),
(424,'Director of Finance and Accounting','Director','Finance / Accounting','Senior Management'),
(441,'Director Of Hr Operations','Director','Human Resources','Senior Management'),
(476,'Director of Marketing and Communications','Director','Marketing','Senior Management'),
(506,'Director of Product Marketing','Director','Marketing','Senior Management'),
(520,'Director of Security Operations','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(535,'Director Of Transportation','Director','Logistics / Transportation','Senior Management'),
(578,'Director, Financial Planning & Analysis','Director','Finance / Accounting','Senior Management'),
(593,'Director, Human Resources','Director','Human Resources','HR Systems Administration'),
(596,'Director, Information Systems','Director','IT / Computers / Electronics','IT Systems Management'),
(625,'Director, Sales','Director','Sales','Sales'),
(673,'Executive Vice President & Chief Operating Officer','C-Level','Executives','COO / Chief Operations Officer'),
(675,'Executive Vice President and CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(688,'Executive Vice President, Chief Operating Officer','C-Level','Executives','COO / Chief Operations Officer'),
(728,'Founder, President & CEO','C-Level','Executives','CEO'),
(771,'Head of Talent','Director','Human Resources','Talent Management'),
(809,'Human Resources Partner','Manager','Human Resources','General Management'),
(847,'Inside Sales Manager','Manager','Sales','Sales'),
(854,'Internet Sales Manager','Manager','Sales','Sales'),
(947,'Manager, Financial Planning and Analysis','Manager','Finance / Accounting','Financial Planning / Advising'),
(968,'Manager, Purchasing','Manager','Logistics / Transportation','Purchasing'),
(975,'Manager, Talent Development','Manager','Human Resources','Talent Management'),
(978,'Managing Partner','C-Level','Executives','Managing Partner'),
(1078,'President/COO','C-Level','Executives','COO / Chief Operations Officer'),
(1079,'President/Owner','C-Level','Executives','President'),
(1194,'Senior Director, Clinical Pharmacology','Senior Director','Biotech','Pharmacy / Pharmaceutical'),
(1212,'Senior Director, IT','Senior Director','IT / Computers / Electronics','Senior Management'),
(1221,'Senior Director, Technology','Senior Director','IT / Computers / Electronics','Senior Management'),
(1246,'Senior Information Technology Project Manager','Senior Manager','IT / Computers / Electronics','IT Project Management'),
(1275,'Senior Manager, Data Science','Senior Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1281,'Senior Manager, Financial Planning & Analysis','Senior Manager','Finance / Accounting','Financial Planning / Advising'),
(1295,'Senior Manager, Talent Acquisition','Senior Manager','Human Resources','Recruiting / Sourcing'),
(1312,'Senior Recruiting Manager','Senior Manager','Human Resources','Recruiting / Sourcing'),
(1313,'Senior Regional Human Resources Manager','Senior Manager','Human Resources','General Management'),
(1333,'Senior Talent Acquisition Partner','Senior Manager','Human Resources','Talent Management'),
(1352,'Senior Vice President Marketing','Senior VP','Marketing','General Management'),
(1353,'Senior Vice President of Engineering','Senior VP','Engineering','Senior Management'),
(1389,'Software Engineering Manager','Manager','IT / Computers / Electronics','Software / System Architecture'),
(1392,'Software Quality Assurance Manager','Manager','IT / Computers / Electronics','QA & Testing'),
(1411,'SVP, Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(1483,'Vice President of IT','VP','IT / Computers / Electronics','Senior Management'),
(1518,'Vice President, Accounting','VP','Finance / Accounting','Accounting'),
(1530,'Vice President, Employee Relations','VP','Human Resources','Compensation / Benefit Policy'),
(1537,'Vice President, Global Talent Acquisition','VP','Human Resources','Talent Management'),
(1540,'Vice President, Information Security','VP','IT / Computers / Electronics','Cyber Security / Information Security'),
(1552,'Vice President, Software Engineering','VP','IT / Computers / Electronics','Software Engineer'),
(1578,'VP of IT','VP','IT / Computers / Electronics','Senior Management'),
(1593,'VP, Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(184,'Chief Learning Officer','C-Level','Executives','CLO / Chief Learning Office'),
(210,'Chief Supply Chain Officer','C-Level','Logistics / Transportation','Supply Chain Management'),
(244,'Co-Founder and COO','C-Level','Executives','COO / Chief Operations Officer'),
(320,'Director Accounting','Director','Finance / Accounting','Accounting'),
(387,'Director of Cloud Operations','Director','IT / Computers / Electronics','IT Infrastructure'),
(393,'Director of Construction','Director','Building Construction','Senior Management'),
(398,'Director of Customer Service','Director','Customer Support / Client Services','Senior Management'),
(438,'Director of Global Payroll','Director','Human Resources','Payroll / Benefits'),
(455,'Director of Information Technology','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(496,'Director of People and Culture','Director','Human Resources','Senior Management'),
(554,'Director, Clinical Research','Director','Biotech','Clinical Research'),
(555,'Director, Cloud Operations','Director','IT / Computers / Electronics','IT Infrastructure'),
(561,'Director, Corporate Accounting','Director','Finance / Accounting','Accounting'),
(562,'Director, Cyber Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(585,'Director, HR','Director','Human Resources','Senior Management'),
(594,'Director, Human Resources Business Partner','Director','Human Resources','Senior Management'),
(631,'Director, Supply Chain Management','Director','Logistics / Transportation','Supply Chain Management'),
(692,'Field Marketing Manager','Manager','Marketing','General Management'),
(693,'Field Sales Manager','Manager','Sales','Sales'),
(703,'Financial Director','Director','Finance / Accounting','Senior Management'),
(715,'Founder / CEO','C-Level','Executives','CEO'),
(722,'Founder and President','C-Level','Executives','President'),
(727,'Founder, Chairman & CEO','C-Level','Executives','CEO'),
(782,'HR Executive','Manager','Human Resources','General Management'),
(822,'Information Security Operations Manager','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(870,'IT Product Manager','Manager','IT / Computers / Electronics','Product Development'),
(896,'Maintenance Superintendent','Manager','Installation / Maintenance / Repair','General Management'),
(904,'Manager Fp&a','Manager','Finance / Accounting','Financial Planning / Advising'),
(907,'Manager IT','Manager','IT / Computers / Electronics','General Management'),
(954,'Manager, Information Security','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(984,'Marketing and Communications Manager','Manager','Marketing','Marketing Communications'),
(997,'MIS Manager','Manager','IT / Computers / Electronics','IT Systems Management'),
(1122,'Roofing Contractor','Contractor','Building Construction','Roofing'),
(1164,'Senior Director Information Security','Senior Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(1188,'Senior Director of Supply Chain','Senior Director','Logistics / Transportation','Supply Chain Management'),
(1189,'Senior Director of Talent Acquisition','Senior Director','Human Resources','Talent Management'),
(1191,'Senior Director Regulatory Affairs','Senior Director','Legal','Regulatory / Compliance'),
(1193,'Senior Director Supply Chain','Senior Director','Logistics / Transportation','Supply Chain Management'),
(1211,'Senior Director, Information Technology','Senior Director','IT / Computers / Electronics','Senior Management'),
(1216,'Senior Director, Marketing','Senior Director','Marketing','General Management'),
(1233,'Senior HR Director','Senior Director','Human Resources','Senior Management'),
(1235,'Senior Hris Manager','Senior Manager','Human Resources','HR Systems Administration'),
(1266,'Senior Manager Software Engineering','Senior Manager','IT / Computers / Electronics','Software Engineer'),
(1278,'Senior Manager, Digital Marketing','Senior Manager','Marketing','Digital Marketing'),
(1294,'Senior Manager, Supply Chain','Senior Manager','Logistics / Transportation','Supply Chain Management'),
(1341,'Senior Vice President and CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(1362,'Senior Vice President, Finance','Senior VP','Finance / Accounting','Senior Management'),
(1364,'Senior Vice President, Human Resources','Senior VP','Human Resources','General Management'),
(1365,'Senior Vice President, Information Technology','Senior VP','IT / Computers / Electronics','Senior Management'),
(1409,'SVP Finance','Senior VP','Finance / Accounting','Senior Management'),
(1475,'Vice President of Finance and Administration','VP','Finance / Accounting','Senior Management'),
(1488,'Vice President of Marketing and Communications','VP','Marketing','Senior Management'),
(1490,'Vice President of Purchasing','VP','Logistics / Transportation','Purchasing'),
(1509,'Vice President Sales & Marketing','VP','Marketing','Senior Management'),
(1515,'Vice President Talent Management','VP','Human Resources','Talent Management'),
(1550,'Vice President, Sales & Marketing','VP','Marketing','Senior Management'),
(1556,'VP & Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(1587,'Vp Purchasing','VP','Logistics / Transportation','Purchasing'),
(31,'Area Director of Human Resources','Director','Human Resources','Senior Management'),
(36,'Assistant Director of Finance','Senior Manager','Finance / Accounting','General Management'),
(38,'Assistant Director of Nursing','Senior Manager','Medical and Health','Nursing / Hospital'),
(45,'Associate Director Human Resources','Senior Manager','Human Resources','General Management'),
(56,'Audit Supervisor','Supervisor','Finance / Accounting','Audit'),
(63,'Benefits Supervisor','Supervisor','Human Resources','Payroll / Benefits'),
(130,'Chairman, President and CEO','C-Level','Executives','CEO'),
(131,'Chairman/CEO','C-Level','Executives','CEO'),
(134,'Channel Marketing Manager','Manager','Marketing','Channel Marketing'),
(154,'Chief Executive Officer and Board Director','C-Level','Executives','CEO'),
(155,'Chief Executive Officer and Board Member','C-Level','Executives','CEO'),
(179,'Chief Information Officer','C-Level','IT / Computers / Electronics','IT Systems Management'),
(253,'Collections Supervisor','Supervisor','Finance / Accounting','Collections'),
(267,'Compensation Partner','Manager','Human Resources','Compensation / Benefit Policy'),
(276,'COO/CFO','C-Level','Executives','COO / Chief Operations Officer'),
(287,'Creative Director','Director','Creative / Design','Creative Direction'),
(314,'Desktop Support Manager','Manager','IT / Computers / Electronics','System Admin / Desktop Support'),
(324,'Director Benefits','Director','Human Resources','Payroll / Benefits'),
(344,'Director HR','Director','Human Resources','Senior Management'),
(345,'Director HRIS','Director','Human Resources','HR Systems Administration'),
(367,'Director Marketing','Director','Marketing','Senior Management'),
(369,'Director of Accounting','Director','Finance / Accounting','Senior Management'),
(465,'Director of Machine Learning','Director','IT / Computers / Electronics','Business Intelligence / Data Science'),
(472,'Director Of Marketing & Communications','Director','Marketing','Marketing Communications'),
(495,'Director of People & Culture','Director','Human Resources','Senior Management'),
(498,'Director of Pharmaceutical Development','Director','Biotech','Pharmacy / Pharmaceutical'),
(501,'Director of Pharmacy Operations','Director','Biotech','Pharmacy / Pharmaceutical'),
(541,'Director Supply Chain','Director','Logistics / Transportation','Supply Chain Management'),
(553,'Director, Clinical Pharmacology','Director','Biotech','Pharmacy / Pharmaceutical'),
(570,'Director, Engineering','Director','Engineering','Senior Management'),
(609,'Director, Logistics','Director','Logistics / Transportation','Logistics'),
(682,'Executive Vice President and COO','C-Level','Executives','COO / Chief Operations Officer'),
(731,'FP&A Director','Director','Finance / Accounting','Financial Planning / Advising'),
(734,'General Accounting Manager','Manager','Finance / Accounting','Accounting'),
(741,'Geographic Information Systems Manager','Manager','IT / Computers / Electronics','IT Systems Management'),
(744,'Global Chief Information Security Officer','C-Level','Executives','CISO / Chief Information Security Officer'),
(751,'Global Supply Manager','Manager','Logistics / Transportation','Supply Chain Management'),
(774,'Hiring Manager','Manager','Human Resources','Recruiting / Sourcing'),
(794,'Human Resource Information System Manager','Manager','Human Resources','HR Systems Administration'),
(844,'Information Technology Support Manager','Manager','IT / Computers / Electronics','System Admin / Desktop Support'),
(888,'Lead Software Developer','Senior Employee','IT / Computers / Electronics','Software Development'),
(909,'Manager of Accounting','Manager','Finance / Accounting','Accounting'),
(942,'Manager, Corporate Accounting','Manager','Finance / Accounting','Accounting'),
(950,'Manager, HRIS','Manager','Human Resources','HR Systems Administration'),
(977,'Managing Director, Human Resources','Senior Director','Human Resources','Senior Management'),
(1019,'Owner/CEO','C-Level','Executives','CEO'),
(1020,'Owner/operator','Owner','Executives','Owner / Co-owner'),
(1171,'Senior Director of Devops','Senior Director','IT / Computers / Electronics','Devops & Application Management'),
(1183,'Senior Director of Payroll','Senior Director','Human Resources','Payroll / Benefits'),
(1204,'Senior Director, Global Human Resources','Senior Director','Human Resources','Senior Management'),
(1218,'Senior Director, Software Development','Senior Director','IT / Computers / Electronics','Software Development'),
(1256,'Senior Manager Finance','Senior Manager','Finance / Accounting','General Management'),
(1257,'Senior Manager Financial Planning Analysis','Senior Manager','Finance / Accounting','Financial Planning / Advising'),
(1283,'Senior Manager, Global Payroll','Senior Manager','Human Resources','Payroll / Benefits'),
(1289,'Senior Manager, Marketing','Senior Manager','Marketing','General Management'),
(1302,'Senior Marketing Manager','Senior Manager','Marketing','Senior Management'),
(1315,'Senior Sales Manager','Senior Manager','Sales','General Management'),
(1386,'Software Engineering Lead','Senior Employee','IT / Computers / Electronics','Software Engineer'),
(1399,'Supervisor, Accounts Payable','Supervisor','Finance / Accounting','Accounts Payable / Receivable'),
(1422,'Talent Partner','Manager','Human Resources','Talent Management'),
(1431,'Telecommunications Manager','Manager','IT / Computers / Electronics','Telecommunications & Wireless'),
(1437,'Total Rewards Manager','Manager','Human Resources','Payroll / Benefits'),
(1444,'Vice President & Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(1447,'Vice President and Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(1451,'Vice President Business Development','VP','Sales','Business Development'),
(1485,'Vice President of Manufacturing','VP','Manufacturing / Production / Operations','General Management'),
(1506,'Vice President Purchasing','VP','Logistics / Transportation','Purchasing'),
(1514,'Vice President Talent Acquisition','VP','Human Resources','Talent Management'),
(1519,'Vice President, Benefits','VP','Human Resources','Payroll / Benefits'),
(1529,'Vice President, Digital Marketing','VP','Marketing','Digital Marketing'),
(1531,'Vice President, Engineering','VP','Engineering','Senior Management'),
(1534,'Vice President, Financial Planning & Analysis','VP','Finance / Accounting','Financial Planning / Advising'),
(1553,'Vice President, Supply Chain','VP','Logistics / Transportation','Supply Chain Management'),
(1554,'Vice President, Talent Acquisition','VP','Human Resources','Talent Management'),
(1555,'Vice President, Talent Management','VP','Human Resources','Talent Management'),
(1561,'VP Engineering','VP','Engineering','General Management'),
(1564,'VP HR','VP','Human Resources','Senior Management'),
(1573,'VP Of HR','VP','Human Resources','Senior Management'),
(1585,'VP Operations','VP','Manufacturing / Production / Operations','Operations'),
(1600,'VP, Information Security Officer','VP','IT / Computers / Electronics','Cyber Security / Information Security'),
(1602,'VP, Information Technology','VP','IT / Computers / Electronics','Senior Management'),
(1606,'Warehouse Operations Manager','Manager','Logistics / Transportation','Shipping / Receiving / Warehousing'),
(21,'Accounts Payable Supervisor','Supervisor','Finance / Accounting','Accounts Payable/Receivable'),
(59,'Benefits & Compensation Manager','Manager','Human Resources','Compensation / Benefit Policy'),
(62,'Benefits Operations Manager','Manager','Human Resources','Payroll / Benefits'),
(64,'BI Manager','Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(97,'CEO and Chairman of the Board','C-Level','Executives','CEO'),
(102,'CEO and Cofounder','C-Level','Executives','CEO'),
(112,'CEO/Owner','C-Level','Executives','CEO'),
(117,'CFO/COO','C-Level','Executives','CFO / Chief Financial Officer'),
(129,'Chairman, President & CEO','C-Level','Executives','CEO'),
(136,'Chief Accounting Officer','C-Level','Executives','Other CXO'),
(160,'Chief Financial and Operating Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(166,'Chief Financial Officer and Treasurer','C-Level','Executives','CFO / Chief Financial Officer'),
(192,'Chief of Staff to CEO','C-Level','Executives','CEO'),
(199,'Chief People & Culture Officer','C-Level','Executives','CPO / Chief People Officer'),
(200,'Chief People and Culture Officer','C-Level','Executives','CPO / Chief People Officer'),
(208,'Chief Software Architect','C-Level','IT / Computers / Electronics','Software / System Architecture'),
(235,'Co Founder and CEO','C-Level','Executives','CEO'),
(247,'Cofounder & CEO','C-Level','Executives','CEO'),
(280,'Corporate Director of Human Resources','Director','Human Resources','Senior Management'),
(381,'Director Of Business Operations','Director','Business','Senior Management'),
(384,'Director of Clinical Research','Director','Biotech','Clinical Research'),
(391,'Director of Compensation & Benefits','Director','Human Resources','Compensation / Benefit Policy'),
(435,'Director of Financial Planning and Analysis','Director','Finance / Accounting','General Management'),
(448,'Director of Information Security Services','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(476,'Director of Marketing and Communications','Director','Marketing','General Management'),
(502,'Director of Plant Operations','Director','Manufacturing / Production / Operations','Plant Management'),
(521,'Director of Social Media','Director','Marketing','Social Media'),
(539,'Director Software Development','Director','IT / Computers / Electronics','Software Development'),
(551,'Director, Channel Marketing','Director','Marketing','Channel Marketing'),
(552,'Director, Clinical Operations','Director','Medical and Health','Hospital / Clinic'),
(567,'Director, Devops','Director','IT / Computers / Electronics','Devops & Application Management'),
(604,'Director, It Infrastructure & Operations','Director','IT / Computers / Electronics','IT Infrastructure'),
(613,'Director, Marketing Communications','Director','Marketing','Marketing Communications'),
(618,'Director, People Operations','Director','Human Resources','Senior Management'),
(620,'Director, Pharmacology','Director','Biotech','Pharmacy / Pharmaceutical'),
(624,'Director, Purchasing','Director','Logistics / Transportation','Purchasing'),
(642,'Electrical Engineering Manager','Manager','Engineering','Electrical / Electronics Engineering'),
(647,'Engineering Director','Director','Engineering','General Management'),
(656,'Evp & Chief Financial Officer','C-Level','Executives','CFO / Chief Financial Officer'),
(659,'Evp Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(661,'Evp, Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(679,'Executive Vice President and Chief Information Officer','C-Level','Executives','CIO / Chief Information Officer'),
(683,'Executive Vice President Chief Operating Officer','C-Level','Executives','COO / Chief Operations Officer'),
(689,'Executive Vice President, Human Resources','Executive VP','Human Resources','Senior Management'),
(694,'Finance Business Partner','Manager','Finance / Accounting','General Management'),
(733,'Front End Manager','Manager','IT / Computers / Electronics','Web Developer'),
(736,'General Counsel & Chief Compliance Officer','C-Level','Executives','CCO / Chief Compliance Officer'),
(737,'General Counsel and Chief Compliance Officer','C-Level','Executives','CCO / Chief Compliance Officer'),
(768,'Head Of People','Director','Human Resources','General Management'),
(797,'Human Resources and Payroll Manager','Manager','Human Resources','Payroll / Benefits'),
(824,'Information System Manager','Manager','IT / Computers / Electronics','General Management'),
(846,'Inside Sales Account Manager','Manager','Sales','Sales'),
(853,'International Accounting Manager','Manager','Finance / Accounting','Accounting'),
(859,'IT Application Manager','Manager','IT / Computers / Electronics','Devops & Application Management'),
(864,'IT Director, Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(899,'Manager Accounting','Manager','Finance / Accounting','Accounting'),
(901,'Manager Compensation','Manager','Human Resources','Compensation / Benefit Policy'),
(902,'Manager Finance','Manager','Finance / Accounting','General Management'),
(910,'Manager of Benefits','Manager','Human Resources','Payroll / Benefits'),
(912,'Manager of Cyber Security','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(935,'Manager, Accounts Payable','Manager','Finance / Accounting','Accounts Payable / Receivable'),
(943,'Manager, Customer Success','Manager','Customer Support / Client Services','Customer Service / Support'),
(949,'Manager, HR Operations','Manager','Human Resources','General Management'),
(960,'Manager, IT Infrastructure','Manager','IT / Computers / Electronics','IT Infrastructure'),
(973,'Manager, Supply Chain','Manager','Logistics / Transportation','Supply Chain Management'),
(990,'Marketing Executive','Manager','Marketing','General Management'),
(996,'Medical Director','Director','Medical and Health','General Management'),
(1021,'Partner','Manager','Executives','Partner'),
(1060,'President & General Manager','C-Level','Executives','President'),
(1065,'President and CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(1074,'President, COO','C-Level','Executives','COO / Chief Operations Officer'),
(1093,'Purchasing Supervisor','Supervisor','Logistics / Transportation','Purchasing'),
(1094,'Real Estate Paralegal','Individual Contributor','Legal','Real Estate'),
(1108,'Regional Recruitment Manager','Manager','Human Resources','Recruiting / Sourcing'),
(1168,'Senior Director IT','Senior Director','IT / Computers / Electronics','General Management'),
(1201,'Senior Director, Finance','Senior Director','Finance / Accounting','General Management'),
(1217,'Senior Director, Product Marketing','Senior Director','Marketing','Brand / Product Marketing'),
(1229,'Senior Financial Manager','Senior Manager','Finance / Accounting','General Management'),
(1230,'Senior General Manager','C-Level','Executives','General Manager'),
(1238,'Senior Human Resources Director','Senior Director','Human Resources','Senior Management'),
(1247,'Senior IT Director','Senior Director','IT / Computers / Electronics','Senior Management'),
(1251,'Senior Logistics Manager','Senior Manager','Logistics / Transportation','Logistics'),
(1252,'Senior Manager Accounting','Senior Manager','Finance / Accounting','Accounting'),
(1269,'Senior Manager Talent Acquisition','Senior Manager','Human Resources','Recruiting / Sourcing'),
(1282,'Senior Manager, Global Compensation','Senior Manager','Human Resources','Compensation / Benefit Policy'),
(1287,'Senior Manager, IT','Senior Manager','IT / Computers / Electronics','General Management'),
(1298,'Senior Marketing Communications Manager','Senior Manager','Marketing','Marketing Communications'),
(1336,'Senior Vice President & CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(1346,'Senior Vice President and Chief Operating Officer','C-Level','Executives','COO / Chief Operations Officer'),
(1347,'Senior Vice President and Chief Technology Officer','C-Level','Executives','CTO / Chief Technology Officer'),
(1376,'Software Development Engineer','Individual Contributor','IT / Computers / Electronics','Software Development'),
(1405,'SVP & CIO','C-Level','Executives','CIO / Chief Information Officer'),
(1413,'SVP, Chief People Officer','C-Level','Executives','CPO / Chief People Officer'),
(1471,'Vice President of Data Science','VP','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1480,'Vice President of Information Security','VP','IT / Computers / Electronics','Cyber Security / Information Security'),
(1494,'Vice President of Sales','VP','Sales','General Management'),
(1495,'Vice President of Sales & Marketing','VP','Marketing','Senior Management'),
(1505,'Vice President of Talent Acquisition','VP','Human Resources','Talent Management'),
(1545,'Vice President, IT Infrastructure','VP','IT / Computers / Electronics','IT Infrastructure'),
(1582,'VP of Sales','VP','Sales','Senior Management'),
(42,'Assistant Vice President Human Resources','VP','Human Resources','Senior Management'),
(43,'Assistant Vice President, Human Resources','VP','Human Resources','Senior Management'),
(47,'Associate Director, Software Engineering','Director','IT / Computers / Electronics','Software Engineer'),
(58,'AVP, Human Resources','VP','Human Resources','Senior Management'),
(82,'CEO & Chairman','C-Level','Executives','CEO'),
(86,'CEO & Cofounder','C-Level','Executives','CEO'),
(96,'CEO and Board Member','C-Level','Executives','CEO'),
(137,'Chief Commercial Officer','C-Level','Executives','Other CXO'),
(139,'Chief Customer Officer','C-Level','Customer Support / Client Services','Senior Management'),
(146,'Chief Diversity Officer','C-Level','Human Resources','Diversity Management / EEO / Compliance'),
(149,'Chief Executive Officer & Co Founder','C-Level','Executives','CEO'),
(179,'Chief Information Officer','C-Level','IT / Computers / Electronics','IT Infrastructure'),
(183,'Chief Investment Officer','C-Level','Executives','Other CXO'),
(189,'Chief Marketing Officer','C-Level','Marketing','Senior Management'),
(204,'Chief Product and Technology Officer','C-Level','Executives','CTO / Chief Technology Officer'),
(231,'Co Founder','C-Level','Executives','Owner / Co-owner'),
(301,'Customer Support Manager','Manager','Customer Support / Client Services','Customer Service / Support'),
(319,'Direct Marketing Manager','Manager','Marketing','Direct Marketing'),
(340,'Director Finance','Director','Finance / Accounting','General Management'),
(402,'Director of Cyber Security Operations','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(404,'Director of Data Center Operations','Director','IT / Computers / Electronics','Data Center'),
(429,'Director of Financial Analysis','Director','Finance / Accounting','Financial Analysis / Research'),
(473,'Director of Marketing and Business Development','Director','Marketing','Senior Management'),
(478,'Director of Marketing and Public Relations','Director','Marketing','Public Relations'),
(499,'Director of Pharmacology','Director','Biotech','Pharmacy / Pharmaceutical'),
(519,'Director of Sales Operations','Director','Sales','Sales Operations'),
(536,'Director of Warehouse Operations','Director','Logistics / Transportation','Shipping / Receiving / Warehousing'),
(560,'Director, Compensation and Benefits','Director','Human Resources','Compensation / Benefit Policy'),
(563,'Director, Cyber Security Operations','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(579,'Director, Fp&A','Director','Finance / Accounting','Financial Planning / Advising'),
(607,'Director, IT Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(640,'Ecommerce Marketing Manager','Manager','Marketing','Digital Marketing'),
(644,'Employee Benefits Service Manager','Manager','Human Resources','Payroll / Benefits'),
(658,'Evp & Coo','C-Level','Executives','COO / Chief Operations Officer'),
(674,'Executive Vice President & CIO','C-Level','Executives','CIO / Chief Information Officer'),
(684,'Executive Vice President of Finance','Executive VP','Finance / Accounting','Senior Management'),
(700,'Financial Accounting Manager','Manager','Finance / Accounting','Accounting'),
(707,'Financial Planning Manager','Manager','Finance / Accounting','Financial Planning / Advising'),
(752,'Group CEO','C-Level','Executives','CEO'),
(776,'Hr and Payroll Manager','Manager','Human Resources','Payroll / Benefits'),
(777,'HR Benefits Manager','Manager','Human Resources','Payroll / Benefits'),
(908,'Manager It Infrastructure','Manager','IT / Computers / Electronics','IT Infrastructure'),
(920,'Manager of Information Security','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(941,'Manager, Compensation & Benefits','Manager','Human Resources','Compensation / Benefit Policy'),
(961,'Manager, Logistics','Manager','Logistics / Transportation','Logistics'),
(985,'Marketing Communications Director','Director','Marketing','Marketing Communications'),
(1049,'Plant Engineering Manager','Manager','Engineering','Plant Engineering'),
(1073,'President, Chief Executive Officer','C-Level','Executives','CEO'),
(1075,'President/ CEO','C-Level','Executives','CEO'),
(1124,'Sales & Marketing Manager','Manager','Marketing','General Management'),
(1139,'Salesperson','Individual Contributor','Sales','Sales'),
(1176,'Senior Director of Information Security','Senior Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(1179,'Senior Director of Infrastructure and Information Security','Senior Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(1186,'Senior Director of Product Marketing','Senior Director','Marketing','Brand / Product Marketing'),
(1190,'Senior Director Product Marketing','Senior Director','Marketing','Brand / Product Marketing'),
(1205,'Senior Director, Global Marketing','Senior Director','Marketing','Senior Management'),
(1207,'Senior Director, HR Business Partner','Senior Director','Human Resources','Senior Management'),
(1214,'Senior Director, IT Infrastructure','Senior Director','IT / Computers / Electronics','Senior Management'),
(1219,'Senior Director, Software Engineering','Senior Director','IT / Computers / Electronics','Software Engineer'),
(1225,'Senior Finance Director','Senior Director','Finance / Accounting','Senior Management'),
(1236,'Senior Human Resource Manager','Senior Manager','Human Resources','General Management'),
(1268,'Senior Manager Supply Chain Management','Senior Manager','Logistics / Transportation','Supply Chain Management'),
(1279,'Senior Manager, Executive Compensation','Senior Manager','Human Resources','Compensation / Benefit Policy'),
(1286,'Senior Manager, Information Security','Senior Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(1291,'Senior Manager, Product Marketing','Senior Manager','Marketing','Brand / Product Marketing'),
(1292,'Senior Manager, Software Development','Senior Manager','IT / Computers / Electronics','Software Development'),
(1332,'Senior Systems Analyst','Senior Employee','IT / Computers / Electronics','System Analysis'),
(1356,'Senior Vice President, CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(1391,'Software Project Manager','Manager','IT / Computers / Electronics','IT Project Management'),
(1406,'SVP and CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(1414,'SVP, Chief Technology Officer','C-Level','Executives','CTO / Chief Technology Officer'),
(1438,'Transportation Logistics Manager','Manager','Logistics / Transportation','Logistics'),
(1457,'Vice President Financial Advisor','VP','Finance / Accounting','Financial Planning / Advising'),
(1476,'Vice President of Finance and CFO','C-Level','Executives','CFO / Chief Financial Officer'),
(1491,'Vice President of Real Estate','VP','Real Estate','Senior Management'),
(1592,'VP Supply Chain','VP','Logistics / Transportation','Supply Chain Management'),
(1609,'Web Developer','Individual Contributor','IT / Computers / Electronics','Web Developer'),
(1,'3D Animator','Individual Contributor','Creative / Design','Animation / Multimedia'),
(19,'Accounts Payable Manager','Manager','Finance / Accounting','General Management'),
(33,'Area Sales Director','Director','Sales','Sales'),
(39,'Assistant Human Resources Director','Director','Human Resources','Senior Management'),
(46,'Associate Director of Information Technology','Director','IT / Computers / Electronics','Senior Management'),
(52,'Associate Vice President, Human Resources','VP','Human Resources','Senior Management'),
(78,'Business Owner','C-Level','Executives','Owner / Co-owner'),
(93,'CEO / Owner','C-Level','Executives','CEO'),
(103,'CEO and Executive Director','C-Level','Executives','CEO'),
(108,'CEO Cofounder','C-Level','Executives','CEO'),
(109,'CEO/Co Founder','C-Level','Executives','CEO'),
(127,'Chairman of the Board and Chief Executive Officer','C-Level','Executives','CEO'),
(128,'Chairman, CEO and Founder','C-Level','Executives','CEO'),
(145,'Chief Digital and Technology Officer','C-Level','Executives','CTO / Chief Technology Officer'),
(165,'Chief Financial Officer & Treasurer','C-Level','Executives','CFO / Chief Financial Officer'),
(180,'Chief Information Officer and Vice President of Analytics','C-Level','Executives','CIO / Chief Information Officer'),
(185,'Chief Legal Officer','C-Level','Executives','Other CXO'),
(186,'Chief Marketing and Communications Officer','C-Level','Executives','CMO / Chief Marketing Officer'),
(191,'Chief Nursing Officer','C-Level','Medical and Health','Nursing / Hospital'),
(205,'Chief Product Officer','C-Level','Executives','Other CXO'),
(250,'CoFounder, CEO','C-Level','Executives','CEO'),
(254,'Commercial Finance Manager','Manager','Finance / Accounting','General Management'),
(255,'Commercial Sales Manager','Manager','Sales','Sales'),
(257,'Compensation & Benefits Director','Director','Human Resources','Compensation / Benefit Policy'),
(262,'Compensation Business Partner','Manager','Human Resources','Compensation / Benefit Policy'),
(246,'Co-President','C-Level','Executives','President'),
(288,'Credit and Collections Manager','Manager','Finance / Accounting','Collections'),
(289,'Credit Collections Manager','Manager','Finance / Accounting','Collections'),
(295,'Customer Care Manager','Manager','Customer Support / Client Services','Customer Service / Support'),
(321,'Director Accounts Payable','Director','Finance / Accounting','Accounts Payable / Receivable'),
(333,'Director Corporate Accounting','Director','Finance / Accounting','Accounting'),
(338,'Director Digital Marketing','Director','Marketing','Digital Marketing'),
(342,'Director Global IT Infrastructure and Environment','Director','IT / Computers / Electronics','IT Infrastructure'),
(351,'Director Information Systems','Director','IT / Computers / Electronics','IT Systems Management'),
(354,'Director Information Technology and Cyber Security','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(358,'Director Information Technology Services','Director','IT / Computers / Electronics','Senior Management'),
(366,'Director IT Security Risk and Compliance','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(370,'Director Of Accounting And Financial Reporting','Director','Finance / Accounting','Accounting'),
(375,'Director of Accounts Receivable','Director','Finance / Accounting','Accounts Payable / Receivable'),
(395,'Director of Corporate Accounting','Director','Finance / Accounting','Corporate'),
(411,'Director of Ecommerce & Digital Marketing','Director','Marketing','Digital Marketing'),
(424,'Director of Finance and Accounting','Director','Finance / Accounting','General Management'),
(430,'Director of Financial Planning','Director','Finance / Accounting','Financial Planning / Advising'),
(431,'Director of Financial Planning & Analysis','Director','Finance / Accounting','Financial Planning / Advising'),
(435,'Director of Financial Planning and Analysis','Director','Finance / Accounting','Financial Analysis / Research'),
(437,'Director of Global Compensation','Director','Human Resources','Compensation / Benefit Policy'),
(174,'Chief Human Resources Officer','C-Level','Executives','CHRO / Chief Human Resource Officer'),
(12,'Accounting Manager','Manager','Finance / Accounting','Accounting'),
(1056,'President & CEO','C-Level','Executives','CEO'),
(1087,'Production Manager','Manager','Manufacturing / Production / Operations','Production'),
(290,'Credit Manager','Manager','Finance / Accounting','Credit Review / Analysis'),
(1418,'Systems Manager','Manager','IT / Computers / Electronics','IT Systems Management'),
(76,'Business Intelligence Manager','Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(55,'Audit Manager','Manager','Finance / Accounting','Audit'),
(72,'Brand Manager','Manager','Marketing','Brand / Product Marketing'),
(380,'Director of Business Intelligence','Director','IT / Computers / Electronics','Business Intelligence / Data Science'),
(388,'Director of Communications','Director','Marketing','Marketing Communications'),
(503,'Director of Procurement','Director','Finance / Accounting','Procurement'),
(256,'Communications Manager','Manager','Marketing','Marketing Communications'),
(845,'Infrastructure Manager','Manager','IT / Computers / Electronics','IT Infrastructure'),
(326,'Director Business Intelligence','Director','IT / Computers / Electronics','Business Intelligence / Data Science'),
(851,'Internal Audit Manager','Manager','Finance / Accounting','Audit'),
(412,'Director of Employee Relations','Director','Human Resources','Compensation / Benefit Policy'),
(44,'Associate Dean','Director','Education','Provost'),
(753,'Group Controller','Manager','Finance / Accounting','Controller'),
(856,'Inventory Manager','Manager','Logistics / Transportation','Inventory Planning / Management'),
(1423,'Tax Accountant','Individual Contributor','Finance / Accounting','Accounting'),
(228,'CMO','C-Level','Executives','CMO / Chief Marketing Officer'),
(654,'Event Manager','Manager','Marketing','Events / Promotional Marketing'),
(291,'CSO','C-Level','Executives','CSO / Chief Security Officer'),
(812,'Human Resources Supervisor','Supervisor','Human Resources','General Management'),
(967,'Manager, Procurement','Manager','Finance / Accounting','Procurement'),
(1524,'Vice President, Controller','VP','Finance / Accounting','Controller'),
(29,'Applications Manager','Manager','IT / Computers / Electronics','Devops & Application Management'),
(634,'Director, Talent Management','Director','Human Resources','Talent Management'),
(1085,'Production Control Manager','Manager','Manufacturing / Production / Operations','Production'),
(1196,'Senior Director, Compensation','Senior Director','Human Resources','Compensation / Benefit Policy'),
(1611,'Wellness Director','Director','Human Resources','Wellness'),
(1082,'Procurement Director','Director','Finance / Accounting','Procurement'),
(1140,'Security Operations Manager','Manager','IT / Computers / Electronics','Cyber Security / Information Security'),
(71,'Brand Director','Director','Marketing','Brand / Product Marketing'),
(79,'Business Unit Controller','Manager','Finance / Accounting','Controller'),
(549,'Director, Business Intelligence','Director','IT / Computers / Electronics','Business Intelligence / Data Science'),
(556,'Director, Communications','Director','Marketing','Marketing Communications'),
(641,'EHS Manager','Manager','Quality Assurance / Safety','Occupational Heal / Safety'),
(1489,'Vice President of Product Management','VP','Business','Product Management'),
(221,'Clinic Manager','Manager','Medical and Health','Hospital / Clinic'),
(650,'Enterprise Implementation Manager','Manager','IT / Computers / Electronics','Enterprise Software Implementation'),
(882,'Labor Relations Manager','Manager','Human Resources','Diversity Management / EEO / Compliance'),
(911,'Manager of Business Intelligence','Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1088,'Production Superintendent','Manager','Manufacturing / Production / Operations','Production'),
(1334,'Senior Tax Accountant','Senior Employee','Finance / Accounting','Accounting'),
(322,'Director Application Development','Director','IT / Computers / Electronics','Devops & Application Management'),
(456,'Director of Internal Audit','Director','Finance / Accounting','Audit'),
(482,'Director of Merchandising','Director','Retail','Merchandise Planning / Buying'),
(507,'Director of Public Relations','Director','Marketing','Public Relations'),
(545,'Director Talent Management','Director','Human Resources','Talent Management'),
(652,'Environmental Manager','Manager','Engineering','Environmental / Geological Engineering'),
(653,'Equipment Manager','Manager','Manufacturing / Production / Operations','Equipment'),
(772,'Head of Total Rewards','Director','Human Resources','Compensation / Benefit Policy'),
(1086,'Production Director','Director','Manufacturing / Production / Operations','Production'),
(1272,'Senior Manager, Business Intelligence','Senior Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1316,'Senior Security Engineer','Senior Employee','IT / Computers / Electronics','Cyber Security / Information Security'),
(1610,'Web Development Manager','Manager','IT / Computers / Electronics','Web Developer'),
(655,'Events Manager','Manager','Marketing','Events / Promotional Marketing'),
(852,'Internal Communications Manager','Manager','Marketing','Marketing Communications'),
(550,'Director, Business Intelligence & Analytics','Director','IT / Computers / Electronics','Business Intelligence / Data Science'),
(599,'Director, Internal Audit','Director','Finance / Accounting','Audit'),
(742,'Global Brand Manager','Manager','Marketing','Brand / Product Marketing'),
(1046,'Pharmacovigilance Manager','Manager','Biotech','Pharmacy / Pharmaceutical'),
(1436,'Test Manager','Manager','IT / Computers / Electronics','QA & Testing'),
(70,'Branch Controller','Manager','Finance / Accounting','Controller'),
(323,'Director Application Services','Director','IT / Computers / Electronics','Devops & Application Management'),
(410,'Director of Diversity, Equity and Inclusion','Director','Human Resources','Diversity Management / EEO / Compliance'),
(486,'Director of Organizational Development','Director','Human Resources','Organizational Development'),
(649,'Enterprise Applications Manager','Manager','IT / Computers / Electronics','Devops & Application Management'),
(651,'Enterprise Project Manager','Manager','IT / Computers / Electronics','IT Project Management'),
(773,'Health and Wellness Director','Director','Human Resources','Wellness'),
(857,'Investment Manager','Manager','Finance / Accounting','Investment Management'),
(900,'Manager Business Intelligence','Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(976,'Manager, Talent Management','Manager','Human Resources','Talent Management'),
(1107,'Regional Procurement Manager','Manager','Finance / Accounting','Procurement'),
(30,'Area Controller','Manager','Finance / Accounting','Controller'),
(325,'Director Business Development','Director','Sales','Business Development'),
(343,'Director Global Procurement','Director','Finance / Accounting','Procurement'),
(359,'Director Internal Audit','Director','Finance / Accounting','Audit'),
(418,'Director of Field Operations','Director','Manufacturing / Production / Operations','Operations'),
(463,'Director of Labor Relations','Director','Human Resources','Diversity Management / EEO / Compliance'),
(526,'Director of Solution Architecture','Director','IT / Computers / Electronics','Software / System Architecture'),
(537,'Director of Wellness','Director','Human Resources','Wellness'),
(538,'Director Security Operations','Director','IT / Computers / Electronics','Cyber Security / Information Security'),
(606,'Director, IT Project Management Office','Director','IT / Computers / Electronics','IT Project Management'),
(617,'Director, Payroll and Benefits Administration','Director','Human Resources','Payroll / Benefits'),
(619,'Director, Pharmaceutical Development','Director','Biotech','Pharmacy / Pharmaceutical'),
(754,'Head of Compensation','Director','Human Resources','Compensation / Benefit Policy'),
(758,'Head of Global Benefits','Director','Human Resources','Payroll / Benefits'),
(775,'HR & Payroll Manager','Manager','Human Resources','Payroll / Benefits'),
(815,'Implementation Manager II','Manager','IT / Computers / Electronics','Enterprise Software Implementation'),
(843,'Information Technology Specialist','Individual Contributor','IT / Computers / Electronics','General Management'),
(848,'Integrated Marketing Manager','Manager','Marketing','Marketing Operations'),
(878,'IT Support Technician','Individual Contributor','IT / Computers / Electronics','System Admin / Desktop Support'),
(893,'Logistics Operations Manager','Manager','Logistics / Transportation','Logistics'),
(1005,'Newscast Director','Director','Journalism / Media / Entertainment','Video / Television'),
(1006,'Nurse Case Manager','Manager','Medical and Health','Nursing / Hospital'),
(1016,'Operations Superintendent','Manager','Manufacturing / Production / Operations','Operations'),
(1034,'Payroll Services Manager','Manager','Human Resources','Payroll / Benefits'),
(1038,'Payroll/Benefits Manager','Manager','Human Resources','Payroll / Benefits'),
(1195,'Senior Director, Communications','Senior Director','Marketing','Marketing Communications'),
(1220,'Senior Director, Talent Management','Senior Director','Human Resources','Talent Management'),
(1255,'Senior Manager Data Analytics','Senior Manager','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1267,'Senior Manager Supply Chain','Senior Manager','Logistics / Transportation','Supply Chain Management'),
(1306,'Senior Principal Software Engineer','Senior Employee','IT / Computers / Electronics','Software Engineer'),
(1361,'Senior Vice President, Chief People Officer','C-Level','Executives','CPO / Chief People Officer'),
(1432,'Terminal Manager','Manager','Logistics / Transportation','Shipping / Receiving / Warehousing'),
(1433,'Territory Business Manager','Manager','Sales','Sales'),
(1470,'Vice President of Business Intelligence','VP','IT / Computers / Electronics','Business Intelligence / Data Science'),
(1548,'Vice President, Marketing and Communications','VP','Marketing','Marketing Communications'),
(1549,'Vice President, Procurement','VP','Finance / Accounting','Procurement'),
(1559,'VP Compensation & Benefits','VP','Human Resources','Compensation / Benefit Policy'),
(1586,'VP Procurement','VP','Finance / Accounting','Procurement')
;
